PHP8 support.
aeviiq/enum pull request #4
Opened 2021-07-20 12:04 UTC by KevinVanSonsbeek

Fixes #3 

Due to some changes the `myclabs/php-enum` package made to the internal behaviour of the Enum object, the AbstractFlag could no longer function while extending it. So it had to be pulled apart, and be made it's own class.

Any logical and needed functionality for it has been taken from the Enum.

2021-07-21 08:11 UTC, nvdbeek approved these changes

2021-07-22 11:59 UTC, nusje2000 requested changes

2021-07-22 11:59 UTC, nusje2000 commented on src/AbstractFlag.php
> -abstract class AbstractFlag extends Enum
NOTE that this change is breaking so a major version should be released for this change. If following the symfony guidelines that is: https://symfony.com/doc/current/contributing/code/bc.html#changing-classes (see "Change parent class")

2021-07-22 11:59 UTC, nusje2000 commented on src/AbstractFlag.php
> +     * @psalm-var array<class-string, array<string, mixed>>
This should be `array<class-string, array<string, int>>`

2021-07-22 11:59 UTC, nusje2000 commented on src/AbstractFlag.php
> +        return array_map(static function ($value) {
`\array_map`

2021-10-26 10:00 UTC, nusje2000 approved these changes

2021-10-26 10:00 UTC, nusje2000 approved these changes

2021-10-26 10:52 UTC, aeviiq approved these changes

2021-10-26 10:53 UTC, merged